name: value_up
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # language pack
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Value_Up dependencies
  http: ^0.13.3
  dio: ^5.0.0
  json_annotation:
  equatable:
  freezed_annotation:
  provider:
  shared_preferences:
  flutter_bloc: 8.0.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  adaptive_action_sheet: ^2.0.2
  flutter_image_slideshow: ^0.1.5
  kakao_flutter_sdk_user: ^1.4.3
  change_app_package_name: ^1.1.0
  flutter_dotenv: ^5.1.0

  # Start camera APIs
  path: ^1.8.3
  camera: ^0.10.5
  path_provider: ^2.0.15
  gallery_saver: ^2.3.2
  image_picker: ^0.8.9
  # End here

  step_progress_indicator: ^1.0.2
  syncfusion_flutter_sliders: ^21.2.9
  intl: ^0.18.0
  chat_bubbles: ^1.4.1
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Value_Up dev_dependencies
  mockito:
  build_runner:
  json_serializable:
  freezed:
  test:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - .env # path to your .env file
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf