// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzFmImM4j6497zgsHCsY9l2HrBEd0wCPI',
    appId: '1:996669819566:android:5bf286edc31522bcb37b3f',
    messagingSenderId: '996669819566',
    projectId: 'valueup-2e010',
    databaseURL: 'https://valueup-2e010-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valueup-2e010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7iP-aJ1Me9MXdL2IKB0iBeyz_zzcnbnI',
    appId: '1:996669819566:ios:92680b1229392373b37b3f',
    messagingSenderId: '996669819566',
    projectId: 'valueup-2e010',
    databaseURL: 'https://valueup-2e010-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valueup-2e010.appspot.com',
    iosBundleId: 'com.example.valueUp',
  );
}
